# Use a imagem oficial do Nginx como base
FROM nginx:alpine

# Crie um diretório para o seu aplicativo
WORKDIR /usr/share/nginx/html


# Exponha a porta 80 para acesso externo
EXPOSE 80

# Comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"] 
